import Footer from "@/components/main/Footer";
import Navbar from "@/components/main/Navbar";
import StarsCanvas from "@/components/main/StarBackground";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "space portfolio",
  description: "Generated by create debarun",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  console.log(inter);
  



  return (
    <html lang="en">

      <head>
      <link rel="icon" href="/pngwing.com.png" />
      </head>

      <body className={`${inter.className} bg-[#030014] overflow-y-scroll overflow-x-hidden `}>
        <StarsCanvas />
        <Navbar />
        {children}</body>
        <Footer />
    </html>
  );
}
